def test_imports():
    import pandas
    import numpy
    import yaml
    import json
    import nltk
    import wordcloud
    import lxml
    import gensim
    import pyLDAvis
    import textblob
    import json_lines
